// Generated by scripts/generate_openapi.py. Do not edit.

export interface components {
  schemas: {
    "ChatAskRequest": {
      "video_id": string;
      "question": string;
      "retrieval_mode"?: "bm25" | "embedding" | "hybrid";
      "source_chunk_ids"?: Array<string>;
    };
    "ChatAskResponse": {
      "message_id"?: string | null;
      "answer": string;
      "retrieval_mode": "bm25" | "embedding" | "hybrid";
      "sources": Array<components["schemas"]["ChatSource"]>;
      "generation": components["schemas"]["GenerationMetadata"];
      "groundedness_warning"?: string | null;
    };
    "ChatHistoryDeleteResponse": {
      "video_id": string;
      "deleted": boolean;
    };
    "ChatHistoryMessage": {
      "message_id": string;
      "video_id": string;
      "question": string;
      "answer": string;
      "retrieval_mode": "bm25" | "embedding" | "hybrid";
      "sources": Array<components["schemas"]["ChatSource"]>;
      "generation": components["schemas"]["GenerationMetadata"];
      "groundedness_warning"?: string | null;
      "created_at": string;
    };
    "ChatHistoryResponse": {
      "video_id": string;
      "messages": Array<components["schemas"]["ChatHistoryMessage"]>;
    };
    "ChatSource": {
      "chunk_id": string;
      "text": string;
      "start_seconds": number;
      "end_seconds": number;
      "score": number;
    };
    "GenerationMetadata": {
      "generation_mode": "llm" | "fallback" | "cached";
      "provider": string;
      "fallback_reason"?: string | null;
    };
    "HTTPValidationError": {
      "detail"?: Array<components["schemas"]["ValidationError"]>;
    };
    "IngestJobCreateRequest": {
      "url": string;
      "idempotency_key"?: string | null;
    };
    "IngestJobErrorResponse": {
      "code": string;
      "message": string;
      "stage": string;
      "retryable": boolean;
    };
    "IngestJobResponse": {
      "job_id": string;
      "video_id": string;
      "status": "pending" | "running" | "retry_wait" | "ready" | "failed" | "cancelled";
      "stage": "pending" | "fetching_metadata" | "fetching_transcript" | "normalizing" | "validating" | "chunking" | "embedding" | "committing" | "complete";
      "target_fingerprint": string | null;
      "retryable": boolean;
      "error": components["schemas"]["IngestJobErrorResponse"] | null;
      "created_at": string;
      "started_at": string | null;
      "finished_at": string | null;
    };
    "QuizQuestion": {
      "question_id": string;
      "question_type": "multiple_choice" | "true_false" | "short_answer";
      "question": string;
      "options": Array<string>;
      "correct_answer": string;
      "explanation": string;
      "source": components["schemas"]["QuizSource"];
    };
    "QuizRequest": {
      "question_count"?: number;
      "difficulty"?: "easy" | "medium" | "hard";
      "question_type"?: "multiple_choice" | "true_false" | "short_answer" | "mixed";
      "mode"?: "practice" | "exam" | "concept_check";
      "force"?: boolean;
      "source_chunk_ids"?: Array<string>;
    };
    "QuizResponse": {
      "video_id": string;
      "difficulty": "easy" | "medium" | "hard";
      "question_type": "multiple_choice" | "true_false" | "short_answer" | "mixed";
      "mode"?: "practice" | "exam" | "concept_check";
      "attempt_id"?: string | null;
      "questions": Array<components["schemas"]["QuizQuestion"]>;
      "sources": Array<components["schemas"]["QuizSource"]>;
      "cached": boolean;
      "generation"?: components["schemas"]["GenerationMetadata"] | null;
    };
    "QuizSource": {
      "chunk_id": string;
      "text": string;
      "start_seconds": number;
      "end_seconds": number;
    };
    "RetrievalDebugChunk": {
      "chunk_id": string;
      "text": string;
      "start_seconds": number;
      "end_seconds": number;
      "score": number;
    };
    "RetrievalDebugRequest": {
      "video_id": string;
      "question": string;
      "retrieval_mode"?: "bm25" | "embedding" | "hybrid";
      "top_k"?: number;
    };
    "RetrievalDebugResponse": {
      "video_id": string;
      "question": string;
      "retrieval_mode": "bm25" | "embedding" | "hybrid";
      "top_k": number;
      "latency_ms": number;
      "chunks": Array<components["schemas"]["RetrievalDebugChunk"]>;
    };
    "StudyNotesRequest": {
      "mode"?: "concise" | "detailed" | "timeline" | "exam_review" | "beginner" | "flashcards" | "concept_map";
      "length"?: "short" | "medium" | "long";
      "learning_goal"?: string | null;
      "force"?: boolean;
    };
    "StudyNotesResponse": {
      "video_id": string;
      "mode"?: "concise" | "detailed" | "timeline" | "exam_review" | "beginner" | "flashcards" | "concept_map";
      "length"?: "short" | "medium" | "long";
      "learning_goal"?: string | null;
      "notes": string;
      "sources": Array<components["schemas"]["StudyNotesSource"]>;
      "cached": boolean;
      "generation": components["schemas"]["GenerationMetadata"];
    };
    "StudyNotesSource": {
      "chunk_id": string;
      "text": string;
      "start_seconds": number;
      "end_seconds": number;
    };
    "SummaryRequest": {
      "mode"?: "short" | "detailed" | "timeline";
      "force"?: boolean;
    };
    "SummaryResponse": {
      "video_id": string;
      "mode": "short" | "detailed" | "timeline";
      "summary": string;
      "sources": Array<components["schemas"]["SummarySource"]>;
      "cached": boolean;
      "generation": components["schemas"]["GenerationMetadata"];
    };
    "SummarySource": {
      "chunk_id": string;
      "text": string;
      "start_seconds": number;
      "end_seconds": number;
    };
    "ValidationError": {
      "loc": Array<string | number>;
      "msg": string;
      "type": string;
      "input"?: unknown;
      "ctx"?: Record<string, unknown>;
    };
    "VideoDeleteResponse": {
      "video_id": string;
      "deleted": boolean;
    };
    "VideoIngestRequest": {
      "url": string;
    };
    "VideoIngestResponse": {
      "video_id": string;
      "title": string;
      "url": string;
      "channel_title"?: string | null;
      "thumbnail_url"?: string | null;
      "duration_seconds": number | null;
      "transcript_language": string | null;
      "chunk_count": number;
      "status": "ready" | "cached" | "failed";
    };
    "VideoMetadataResponse": {
      "video_id": string;
      "title": string;
      "url": string;
      "channel_title"?: string | null;
      "thumbnail_url"?: string | null;
      "duration_seconds": number | null;
      "transcript_language": string | null;
      "chunk_count": number;
      "created_at": string;
      "updated_at": string;
    };
    "VideoRebuildIndexResponse": {
      "video_id": string;
      "rebuilt": boolean;
      "chunk_count": number;
    };
  }
}
