"""create canonical persistence schema

Revision ID: a424b0f1c95b
Revises:
Create Date: 2026-07-16 22:25:57.091589
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a424b0f1c95b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("youtube_video_id", sa.String(length=32), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("channel_title", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "failed",
                name="video_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint("duration_ms IS NULL OR duration_ms >= 0", name=op.f("ck_videos_duration_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_videos_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_youtube_video_id"), ["youtube_video_id"], unique=True)

    op.create_table(
        "ingest_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "retry_wait",
                "ready",
                "failed",
                "cancelled",
                name="ingest_job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "current_stage",
            sa.Enum(
                "pending",
                "fetching_metadata",
                "fetching_transcript",
                "normalizing",
                "validating",
                "chunking",
                "embedding",
                "committing",
                "complete",
                name="ingest_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("retryable", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_ingest_jobs_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_jobs")),
    )
    with op.batch_alter_table("ingest_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingest_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_ingest_jobs_video_id"), ["video_id"], unique=False)

    op.create_table(
        "transcripts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_version", sa.String(length=64), nullable=True),
        sa.Column("language_code", sa.String(length=35), nullable=False),
        sa.Column(
            "transcript_type",
            sa.Enum("manual", "generated", "asr", name="transcript_type", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("normalizer_version", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_transcripts_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcripts")),
        sa.UniqueConstraint("video_id", "provider", "content_hash", name="uq_transcripts_video_provider_hash"),
    )
    with op.batch_alter_table("transcripts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transcripts_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_transcripts_language_code"), ["language_code"], unique=False)
        batch_op.create_index("ix_transcripts_video_active", ["video_id", "is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_transcripts_video_id"), ["video_id"], unique=False)

    op.create_table(
        "index_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("transcript_id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("chunker_version", sa.String(length=64), nullable=False),
        sa.Column("chunker_config", sa.JSON(), nullable=False),
        sa.Column("embedding_provider", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=255), nullable=False),
        sa.Column("embedding_revision", sa.String(length=128), nullable=True),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "building",
                "ready",
                "failed",
                "inactive",
                name="index_version_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("embedding_dimension > 0", name=op.f("ck_index_versions_embedding_dimension_positive")),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
            name=op.f("fk_index_versions_transcript_id_transcripts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_index_versions_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_versions")),
        sa.UniqueConstraint("video_id", "fingerprint", name="uq_index_versions_video_fingerprint"),
    )
    with op.batch_alter_table("index_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_index_versions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_index_versions_transcript_id"), ["transcript_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_index_versions_video_id"), ["video_id"], unique=False)
        batch_op.create_index("ix_index_versions_video_status", ["video_id", "status"], unique=False)

    op.create_table(
        "ingest_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ingest_job_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "pending",
                "fetching_metadata",
                "fetching_transcript",
                "normalizing",
                "validating",
                "chunking",
                "embedding",
                "committing",
                "complete",
                name="ingest_attempt_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "succeeded",
                "failed",
                "skipped",
                name="ingest_attempt_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint("attempt_number > 0", name=op.f("ck_ingest_attempts_attempt_number_positive")),
        sa.CheckConstraint(
            "elapsed_ms IS NULL OR elapsed_ms >= 0", name=op.f("ck_ingest_attempts_elapsed_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["ingest_job_id"],
            ["ingest_jobs.id"],
            name=op.f("fk_ingest_attempts_ingest_job_id_ingest_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_attempts")),
        sa.UniqueConstraint("ingest_job_id", "attempt_number", name="uq_ingest_attempts_job_number"),
    )
    with op.batch_alter_table("ingest_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingest_attempts_ingest_job_id"), ["ingest_job_id"], unique=False)

    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("transcript_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.CheckConstraint("sequence_number >= 0", name=op.f("ck_transcript_segments_sequence_non_negative")),
        sa.CheckConstraint(
            "start_ms >= 0 AND end_ms > start_ms", name=op.f("ck_transcript_segments_timestamp_range_valid")
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
            name=op.f("fk_transcript_segments_transcript_id_transcripts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint("transcript_id", "sequence_number", name="uq_transcript_segments_transcript_sequence"),
    )
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transcript_segments_transcript_id"), ["transcript_id"], unique=False)

    op.create_table(
        "chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("transcript_id", sa.String(length=36), nullable=False),
        sa.Column("index_version_id", sa.String(length=36), nullable=False),
        sa.Column("parent_chunk_id", sa.String(length=36), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "chunk_type",
            sa.Enum("child", "parent", name="chunk_type", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.CheckConstraint("sequence_number >= 0", name=op.f("ck_chunks_sequence_non_negative")),
        sa.CheckConstraint("start_ms >= 0 AND end_ms > start_ms", name=op.f("ck_chunks_timestamp_range_valid")),
        sa.CheckConstraint("token_count > 0", name=op.f("ck_chunks_token_count_positive")),
        sa.ForeignKeyConstraint(
            ["index_version_id"],
            ["index_versions.id"],
            name=op.f("fk_chunks_index_version_id_index_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_chunk_id"], ["chunks.id"], name=op.f("fk_chunks_parent_chunk_id_chunks"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"], ["transcripts.id"], name=op.f("fk_chunks_transcript_id_transcripts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_chunks_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "index_version_id", "chunk_type", "sequence_number", name="uq_chunks_version_type_sequence"
        ),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chunks_index_version_id"), ["index_version_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chunks_parent_chunk_id"), ["parent_chunk_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chunks_transcript_id"), ["transcript_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chunks_video_id"), ["video_id"], unique=False)

    op.create_table(
        "chunk_segments",
        sa.Column("chunk_id", sa.String(length=36), nullable=False),
        sa.Column("transcript_segment_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_chunk_segments_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunks.id"], name=op.f("fk_chunk_segments_chunk_id_chunks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["transcript_segment_id"],
            ["transcript_segments.id"],
            name=op.f("fk_chunk_segments_transcript_segment_id_transcript_segments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chunk_id", "transcript_segment_id", name=op.f("pk_chunk_segments")),
        sa.UniqueConstraint("chunk_id", "position", name="uq_chunk_segments_chunk_position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chunk_segments")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunks_video_id"))
        batch_op.drop_index(batch_op.f("ix_chunks_transcript_id"))
        batch_op.drop_index(batch_op.f("ix_chunks_parent_chunk_id"))
        batch_op.drop_index(batch_op.f("ix_chunks_index_version_id"))

    op.drop_table("chunks")
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_segments_transcript_id"))

    op.drop_table("transcript_segments")
    with op.batch_alter_table("ingest_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingest_attempts_ingest_job_id"))

    op.drop_table("ingest_attempts")
    with op.batch_alter_table("index_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_index_versions_video_status")
        batch_op.drop_index(batch_op.f("ix_index_versions_video_id"))
        batch_op.drop_index(batch_op.f("ix_index_versions_transcript_id"))
        batch_op.drop_index(batch_op.f("ix_index_versions_status"))

    op.drop_table("index_versions")
    with op.batch_alter_table("transcripts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcripts_video_id"))
        batch_op.drop_index("ix_transcripts_video_active")
        batch_op.drop_index(batch_op.f("ix_transcripts_language_code"))
        batch_op.drop_index(batch_op.f("ix_transcripts_is_active"))

    op.drop_table("transcripts")
    with op.batch_alter_table("ingest_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingest_jobs_video_id"))
        batch_op.drop_index(batch_op.f("ix_ingest_jobs_status"))

    op.drop_table("ingest_jobs")
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_videos_youtube_video_id"))
        batch_op.drop_index(batch_op.f("ix_videos_status"))

    op.drop_table("videos")
    # ### end Alembic commands ###
