"""Generate the committed OpenAPI document and frontend TypeScript contracts."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "frontend" / "src" / "shared" / "api" / "openapi.json"
TYPES_PATH = ROOT / "frontend" / "src" / "shared" / "api" / "schema.ts"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    os.environ["PYTHON_DOTENV_DISABLED"] = "1"
    os.environ["LLM_PROVIDER"] = "fallback"
    os.environ["EMBEDDING_PROVIDER"] = "hashing"
    os.environ["VECTOR_STORE_PROVIDER"] = "local_json"
    sys.path.insert(0, str(ROOT / "backend"))

    from app.main import app

    schema_text = json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"
    types_text = _generate_types(app.openapi())
    if args.check:
        stale = [path for path, expected in ((SCHEMA_PATH, schema_text), (TYPES_PATH, types_text)) if _read(path) != expected]
        if stale:
            print("Generated API contracts are stale: " + ", ".join(str(path.relative_to(ROOT)) for path in stale))
            return 1
        return 0

    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(schema_text, encoding="utf-8")
    TYPES_PATH.write_text(types_text, encoding="utf-8")
    return 0


def _generate_types(document: dict[str, Any]) -> str:
    schemas = document.get("components", {}).get("schemas", {})
    lines = ["// Generated by scripts/generate_openapi.py. Do not edit.", "", "export interface components {", "  schemas: {"]
    for name, schema in sorted(schemas.items()):
        lines.append(f"    {json.dumps(name)}: {_type_expression(schema, 4)};")
    lines.extend(["  }", "}", ""])
    return "\n".join(lines)


def _type_expression(schema: dict[str, Any], indent: int) -> str:
    if "$ref" in schema:
        return f'components["schemas"][{json.dumps(schema["$ref"].rsplit("/", 1)[-1])}]'
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    alternatives = schema.get("anyOf") or schema.get("oneOf")
    if alternatives:
        return " | ".join(_type_expression(item, indent) for item in alternatives)
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_primitive(item) for item in schema_type)
    if schema_type == "array":
        return f"Array<{_type_expression(schema.get('items', {}), indent)}>"
    if schema_type == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        prefix = " " * indent
        properties = []
        for name, value in schema.get("properties", {}).items():
            optional = "" if name in required else "?"
            properties.append(f"{prefix}  {json.dumps(name)}{optional}: {_type_expression(value, indent + 2)}")
        if not properties:
            return "Record<string, unknown>"
        return "{\n" + ";\n".join(properties) + f";\n{prefix}}}"
    return _primitive(schema_type)


def _primitive(schema_type: str | None) -> str:
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(
        schema_type, "unknown"
    )


def _read(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.exists() else None


if __name__ == "__main__":
    raise SystemExit(main())
