from typing import Protocol

from app.domain.entities import (
    Chunk,
    ChunkSegmentLink,
    IndexVersion,
    IngestAttempt,
    IngestJob,
    Transcript,
    TranscriptSegment,
    Video,
)


class VideoRepository(Protocol):
    def add(self, video: Video) -> Video: ...

    def get(self, video_id: str) -> Video | None: ...

    def get_by_youtube_id(self, youtube_video_id: str) -> Video | None: ...

    def save(self, video: Video) -> Video: ...

    def list_recent(self, limit: int = 50) -> list[Video]: ...

    def delete(self, video_id: str) -> bool: ...


class IngestJobRepository(Protocol):
    def add(self, job: IngestJob) -> IngestJob: ...

    def get(self, job_id: str) -> IngestJob | None: ...

    def get_by_idempotency_key(self, idempotency_key: str) -> IngestJob | None: ...

    def find_active(self, video_id: str, target_fingerprint: str) -> IngestJob | None: ...

    def list_running(self) -> list[IngestJob]: ...

    def save(self, job: IngestJob) -> IngestJob: ...

    def add_attempt(self, attempt: IngestAttempt) -> IngestAttempt: ...

    def list_attempts(self, job_id: str) -> list[IngestAttempt]: ...


class TranscriptRepository(Protocol):
    def add(self, transcript: Transcript) -> Transcript: ...

    def get(self, transcript_id: str) -> Transcript | None: ...

    def get_version(
        self,
        video_id: str,
        provider: str,
        content_hash: str,
        parser_version: str,
        normalizer_version: str,
    ) -> Transcript | None: ...

    def get_active(self, video_id: str) -> Transcript | None: ...

    def add_segments(self, segments: list[TranscriptSegment]) -> list[TranscriptSegment]: ...

    def list_segments(self, transcript_id: str) -> list[TranscriptSegment]: ...

    def activate(self, video_id: str, transcript_id: str) -> None: ...


class IndexRepository(Protocol):
    def add_version(self, index_version: IndexVersion) -> IndexVersion: ...

    def get_version(self, index_version_id: str) -> IndexVersion | None: ...

    def get_by_fingerprint(self, video_id: str, fingerprint: str) -> IndexVersion | None: ...

    def get_active(self, video_id: str) -> IndexVersion | None: ...

    def list_versions(self, video_id: str) -> list[IndexVersion]: ...

    def save_version(self, index_version: IndexVersion) -> IndexVersion: ...

    def activate(self, video_id: str, index_version_id: str) -> IndexVersion: ...

    def add_chunks(self, chunks: list[Chunk]) -> list[Chunk]: ...

    def add_segment_links(self, links: list[ChunkSegmentLink]) -> list[ChunkSegmentLink]: ...

    def list_chunks(self, index_version_id: str, *, child_only: bool = False) -> list[Chunk]: ...

    def get_chunks(self, index_version_id: str, chunk_ids: list[str]) -> list[Chunk]: ...
